### ISSUE TITLE
Dashboard - Crash when refreshing data on parameter tracking widget of a deleted parameter

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#369]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
While testing the CDP4 dashboard, i found this issue, Refresh the data for a graph where the parameter was just deleted. The an exception is thrown (internal server exception) which makes the CDP4-IME crash. The exception the server (perhaps should not) return makes the app crash which should not happen.

### Steps to Reproduce
  - using the desktop app create a graph widget in the dashboard
  - delete the parameter
  - refresh the data on the widget
  - server returns an exception (https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/106), app crashes

### Logs

  - [x] There are no logs regarding the issue

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 6.0.0-RC2

- Web Services:
  - [x] CDP4 Web Services version:  5.1.0
