### ISSUE TITLE
Crossview error on generating sheet with a single ParameterType

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#693]
### Description
An error occurs when generating the Crossview sheet with a single ParameterType; this is independent of the number of selected elements.

The sheet is still generated, which causes the error to be practically invisible unless you look for it, as all Crossview generation sheets are ignored/hidden via a try-catch block that discards them. This behavior is also present in the ParameterWorksheetGenerator.

### Tasks
* [ ] do not ignore sheet generation errors in CrossviewWorksheet
* [ ] do not ignore sheet generation errors in ParameterWorksheet
* [x] fix described error

### Steps to Reproduce
Setup:
* try to generate a sheet with a single ParameterType

![Capture](https://user-images.githubusercontent.com/65681485/104745059-53394c00-5756-11eb-89bd-fe1d34e2abae.PNG)

### Error
```
"Failed to proceed Method on Excel.Range=>CreateNames."
   at NetOffice.Invoker.MethodReturn(ICOMObject comObject, String name, Object[] paramsArray)
   at NetOffice.CoreMethodExtensions.ExecuteVariantMethodGet(Core value, ICOMObject caller, String name, Object[] paramsArray)
   at NetOffice.ExcelApi.Range.CreateNames(Object top, Object left, Object bottom, Object right)
   at CDP4CrossViewEditor.Generator.CrossviewSheetGenerator.ApplyCellNames(Int32 beginRow,
      int32 beginColumn,
      int32 endRow,
      int32 endColumn)
      in CDP4CrossViewEditor\Generator\CrossviewSheetGenerator.cs:line 457
   at CDP4CrossViewEditor.Generator.CrossviewSheetGenerator.WriteRows()
      in CDP4CrossViewEditor\Generator\CrossviewSheetGenerator.cs:line 283
   at CDP4CrossViewEditor.Generator.CrossviewSheetGenerator.WriteSheet()
      in CDP4CrossViewEditor\Generator\CrossviewSheetGenerator.cs:line 227
   at CDP4CrossViewEditor.Generator.CrossviewSheetGenerator.Rebuild(Application application, Workbook workbook, IEnumerable`1 elementDefinitions, IEnumerable`1 parameterTypes)
      in CDP4CrossViewEditor\Generator\CrossviewSheetGenerator.cs:line 158
```

Error code & HRESULT: -2147467259.
