### ISSUE TITLE
Save manually filled values problems

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#727]
### Tasks
* [x] always persist selected elements
* [x] save only iids for selected EDs/PTs
* [x] only one usage currently displayed per element, needs to be all
* [x] fix elements reordering themselves in the list
* [x] fix missing manually added values

**Comment by cozminvelciu** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.excel.range.applynames?view=excel-pia
